const Sequelize = require('sequelize')
const db = require('../db')

const Comment = db.define('comment', {  //belongs to a user and to a story by association
  content: {                           //creation date automatically generated by postgreSQL
    type: Sequelize.TEXT,
    validate:{
      notEmpty: true
    }
  }
})

module.exports = Comment
